### ISSUE TITLE
Caddy Proxy HTTPS Not Working

### ISSUE THREAD

**Issue by cwre** [JimTim/zeropaste#2]
I'm not sure where exactly the issue is here, but it's probably with how the webservers are interacting between the container and the machine. 

I'm running Caddy on an Arch VPS with a couple other applications running here: https://alexroberts.xyz

Currently, I have caddy to handle /pb as a proxy for :86 which is what I have the container exposing for the VPS. 

Here's the weird stuff...
This is what happens when I try accessing https://alexroberts.xyz/pb with or without the https://
https://pageshot.net/fviodTdRBFESICJd/alexroberts.xyz

This is what happens when I try accessing https://alexroberts.xyz:86
https://pageshot.net/4ypjKhTt1FR5nBch/alexroberts.xyz

It only works when I try accessing alexroberts.xyz:86

I don't really understand why I get two different errors when using HTTPS. I haven't had an issue with other applications, so I was hoping you'd help me debug this.

Here is my docker-compose.yml: 

```
zeropaste:
  image: jimtim/zeropaste
  environment:
    - "PRIMARYCOLOR=cyan darken-2"
    - "ACCENTCOLOR=deep-orange accent-2"
    - "TEXTCOLOR=white"
    - "BACKGROUNDCOLOR=white"
    - "ALWAYSSYNTAX=1"
  ports:
    - "86:80"

ghostblog:
  image: ptimof/ghost
  environment:
    - "GHOST_URL=http://alexroberts.xyz/blog"
    - "MAIL_FROM="
    - "MAIL_HOST="
  ports:
    - "2368:2368"
  volumes:
    - "/home/ishmael/ghostblog:/var/lib/ghost"
```

Let me know if you need anything else from me.

**Comment by JimTim** [comment]
I will look at it. Where does the Caddy Proxy come from? Is this also a docker container?

**Comment by cwre** [comment]
Caddy is just an application on my system. It's running the entirety of my
website.

**Comment by JimTim** [comment]
Can you give me the Caddy proxy setting. Maybe screenshots? Also, I'm just building new images. Can you maybe try. Perhaps the problems have already solved?

**Comment by cwre** [comment]
Caddy handles all the proxies itself. It's set up in a standard Caddyfile.

https://caddyserver.com/

**Comment by JimTim** [comment]
I do not know Caddy and do not know how the proxy works there. I use https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/ in connection with https://hub.docker.com/r/jwilder/nginx-proxy/ and there is no problems. Can you write to Caddy's support and ask them? You can also submit pull requests here.

**Comment by cwre** [comment]
Oh, if you're using letsencrypt, that might be the issue. Do you know if theres a way to turn it off per container spun up? Like a flag I can set? Caddy runs letsencrypt too, so letsencrypting a letsencrypted server might be the issue.

**Comment by JimTim** [comment]
Nope, not https or lesencrypt in the container. My docker-compose config looks like: nginx-proxy, letsencrypt-companion, zeropaste

**Comment by cwre** [comment]
What exact changes did you make to the image?

**Comment by JimTim** [comment]
New baseimage (from: alpine) and new apache configuration

**Comment by cwre** [comment]
Here's my docker-compose.yml

```
zeropaste:
  image: jimtim/zeropaste
  environment:
    - "PRIMARYCOLOR=cyan darken-2"
    - "ACCENTCOLOR=deep-orange accent-2"
    - "TEXTCOLOR=white"
    - "BACKGROUNDCOLOR=white"
    - "ALWAYSSYNTAX=1"
  ports:
    - "9004:8000"
```

Not getting anything on port 9004, and it looks like 80 and 443 are still being exposed... Is that intended?
